### ISSUE TITLE
parse detail

### ISSUE THREAD

**Issue by shcalm** [eksplodo/DoubanReading#1]
next_page = response.xpath('//*[@id="subject_list"]/div[2]/span[5]/a/@href').extract_first(
这个response貌似无法得到下一页的url

**Comment by eksplodo** [comment]
@shcalm 你试试这个：
 ```python
next_page = response.xpath('//span[@class="next"]/a/@href
```

**Comment by shcalm** [comment]
嗯,但是不应该在parse detail这个函数里面调用吧.
应该在 parse group 这个里面吧 
另外 问下,貌似执行一会 ip就会被封了,但是返回的是status是200,所以也不会调用代理..

**Comment by shcalm** [comment]
谢谢哈,..
抓点图书数据.,但是差不多500本 就挂了..

**Comment by eksplodo** [comment]
@shcalm 代理质量好一点应该会好很多。
